#!/bin/sh

HOME=/path/to/your/homedir
PUBLIC=/path/to/public/tools
CMAKE=$PUBLIC/cmake


$CMAKE/bin/cmake -DGMX_HWLOC=off -DBUILD_SHARED_LIBS=ON -DGMX_BUILD_FOR_COVERAGE=on -DCMAKE_BUILD_TYPE=Release -DGMX_CUDA_NB_SINGLE_COMPILATION_UNIT=on -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DGMX_MPI=on -DGMX_GPU=on -DGMX_OPENMP=on -DGMX_GPU_DETECTION_DONE=on  -DGMX_SIMD=AUTO -DCMAKE_INSTALL_PREFIX=$HOME/path/to/install  -DGMX_FFT_LIBRARY=fftw3 -DFFTWF_LIBRARY=$PUBLIC/fftw/lib64/libfftw3f.so -DFFTWF_INCLUDE_DIR=$PUBLIC/fftw/include  -DBLAS_LIBRARIES=$PUBLIC/lapack/lib64/libblas.so -DLAPACK_LIBRARIES=$PUBLIC/lapack/lib64/liblapack.so -DREGRESSIONTEST_DOWNLOAD=OFF -DGMX_DEVELOPER_BUILD=on /path/to/top/CMakeLists.txt

